name: N2 LuaJIT Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LuaJIT
        run: |
          apt-get update && apt-get install luajit -y
      - name: Run Tests
        run: |
          luajit n2.test.lua
